strategy_type = "learning"
config = {
    "strategy_id": "sdnnc",
    "name": "Standard DNN Classifier",
    "parameters": [
        {
            "parameter_id": "layers",
            "label": "Number of layers",
            "type": "int",
            "required": True,
            "default_value": 5,
        },
        {
            "parameter_id": "neurons",
            "label": "Number of neurons per layer",
            "type": "int",
            "required": True,
            "default_value": 200,
        },
        {
            "parameter_id": "batch",
            "label": "Batch size",
            "type": "int",
            "required": True,
            "default_value": 100,
        },
        {
            "parameter_id": "epochs",
            "label": "Number of epochs",
            "type": "int",
            "required": True,
            "default_value": 10,
        },
        {
            "parameter_id": "lr",
            "label": "Starting learning rate",
            "type": "float",
            "required": True,
            "default_value": 0.05,
        },        
    ],
    "grid_search": {
        "small": [
            {
                "layers": 2,
                "neurons": 100,
                "batch": 512,
                "epochs": 5,
                "lr": 0.1,
            },
            {
                "layers": 3,
                "neurons": 100,
                "batch": 512,
                "epochs": 5,
                "lr": 0.1,
            },
            {
                "layers": 4,
                "neurons": 100,
                "batch": 512,
                "epochs": 5,
                "lr": 0.1,
            },
            {
                "layers": 5,
                "neurons": 150,
                "batch": 512,
                "epochs": 5,
                "lr": 0.1,
            },
        ],
        "medium": [
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 5,
                "lr": 0.1,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 2,
                "lr": 0.1,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.1,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 20,
                "lr": 0.1,
            },
        ],
        "large": [
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.025,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.05,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.1,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.2,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.3,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.4,
            },
            {
                "layers": 5,
                "neurons": 200,
                "batch": 512,
                "epochs": 10,
                "lr": 0.5,
            },
        ],
    }
}
